import { Giveaway, Winner, Entry, UserProfile } from '../types';

export const INITIAL_USER: UserProfile = {
  name: 'Alex Rivera',
  username: '@alex92',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  joinedDate: 'Aug 2026',
  telegramConnected: true,
  telegramUsername: '@alex92',
  stats: {
    totalEntries: 12,
    activeEntries: 3,
    totalWins: 0,
  },
};

// Target date: set live draw to 2 hours, 14 mins, 38 secs in future dynamically or fixed
const now = new Date();
const liveDrawTarget = new Date(now.getTime() + (2 * 3600 + 14 * 60 + 38) * 1000).toISOString();
const flashTarget = new Date(now.getTime() + (38 * 60 + 12) * 1000).toISOString();
const dailyTarget = new Date(now.getTime() + (14 * 3600 + 22 * 60) * 1000).toISOString();
const weeklyDrawTarget = new Date(now.getTime() + (5 * 86400 + 12 * 3600) * 1000).toISOString();
const techDrawTarget = new Date(now.getTime() + (1 * 86400 + 4 * 3600) * 1000).toISOString();
const giftDrawTarget = new Date(now.getTime() + (3 * 86400 + 18 * 3600) * 1000).toISOString();
const ps5DrawTarget = new Date(now.getTime() + (6 * 86400 + 8 * 3600) * 1000).toISOString();
const diamondTarget = new Date(now.getTime() + (4 * 86400 + 6 * 3600) * 1000).toISOString();

export const MOCK_GIVEAWAYS: Giveaway[] = [
  {
    id: 'draw-hero-5000',
    title: 'Grand Cash',
    subtitle: 'Grand Draw #130',
    prizeAmount: '$25,000',
    category: 'cash',
    image: '/assets/cutouts/render-golden-sphere.png',
    accentGradient: 'from-purple-500 to-indigo-600',
    isFeatured: true,
    isLive: false,
    endsAt: weeklyDrawTarget,
    totalEntrants: 48500,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sunday, Sep 27 • 9:00 PM EST',
    description: 'Our premier weekly jackpot drawn automatically every Sunday night. Guaranteed zero-cost entry with instant Telegram disbursement upon verified cryptographic draw.',
    seedHash: '0x94f1c8a42b109e23df8812cbb41a0e889a7102f1837',
    tier: 'Grand',
  },
  {
    id: 'draw-live-500',
    title: '$500 CASH Free Giveaway',
    subtitle: 'Official Live Draw closes soon',
    prizeAmount: '$500 CASH',
    category: 'cash',
    image: '/assets/cutouts/render-cash-card.png',
    accentGradient: 'from-indigo-600 to-sky-500',
    isFeatured: true,
    isLive: true,
    endsAt: liveDrawTarget,
    totalEntrants: 4280,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 25, 2026 • 9:00 PM EST',
    description: 'Fast-paced live cash drop. Verified entries drawn immediately when countdown strikes zero. 100% free with instant direct transfer to the selected winner.',
    seedHash: '0x7c94b2a82fa9012cdb482019ff8820c812ef90184b2',
    tier: 'Daily',
  },
  {
    id: 'draw-iphone-16',
    title: 'iPhone 16 Pro Max 256GB',
    subtitle: 'Natural Titanium • Sealed Retail Box',
    prizeAmount: '$1,199 Value',
    category: 'tech',
    image: '/assets/cutouts/iphone-16.png',
    accentGradient: 'from-fuchsia-600 to-pink-500',
    isFeatured: false,
    isLive: false,
    endsAt: techDrawTarget,
    totalEntrants: 9140,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Tomorrow • 8:00 PM EST',
    description: 'Brand new factory sealed iPhone 16 Pro Max in Natural Titanium. Free worldwide express courier delivery provided directly by Aura team.',
    seedHash: '0x539b90ef781a94cdbe33010b91e7c99201a4bc58210',
    tier: 'Weekly',
  },
  {
    id: 'draw-amazon-250',
    title: '$250 Amazon Gift Card',
    subtitle: 'Global digital redemption code',
    prizeAmount: '$250 Gift Card',
    category: 'giftcard',
    image: '/assets/cutouts/gift-250.png',
    accentGradient: 'from-amber-500 to-orange-500',
    isFeatured: false,
    isLive: false,
    endsAt: giftDrawTarget,
    totalEntrants: 3620,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 26, 2026 • 6:00 PM EST',
    description: 'Instant digital code delivered straight to your verified Telegram DM. Usable across any Amazon global storefront with zero expiration date.',
    seedHash: '0x22ab88f4019a7ce82910ba543209ef9810a47321098',
    tier: 'Daily',
  },
  {
    id: 'draw-gold-1000',
    title: 'Crystal Gold $1,000 Sweep',
    subtitle: 'Instant Telegram USD payout',
    prizeAmount: '$1,000 CASH',
    category: 'cash',
    image: '/assets/cutouts/gold-1000.png',
    accentGradient: 'from-amber-400 via-pink-500 to-purple-600',
    isFeatured: false,
    isLive: false,
    endsAt: weeklyDrawTarget,
    totalEntrants: 7850,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 28, 2026 • 10:00 PM EST',
    description: 'High-stakes zero-entry community celebration pool. One lucky entrant takes home $1,000 verified with full cryptographic on-chain seed proof.',
    seedHash: '0x81fa02ec449102b378daef019247cc99318a09fb201',
    tier: 'Weekly',
  },
  {
    id: 'draw-ps5-pro',
    title: 'PlayStation 5 Pro Edition',
    subtitle: '2TB SSD • DualSense Wireless',
    prizeAmount: '$699 Value',
    category: 'tech',
    image: '/assets/cutouts/ps5-dark.png',
    accentGradient: 'from-blue-600 to-cyan-400',
    isFeatured: false,
    isLive: false,
    endsAt: ps5DrawTarget,
    totalEntrants: 6410,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 29, 2026 • 7:00 PM EST',
    description: 'Next-gen gaming power delivered to your doorstep. Includes extra DualSense controller and 12-month PS Plus premium voucher.',
    seedHash: '0x49ca092ef18903cde81a0293847b2c9103e9481aa01',
    tier: 'Weekly',
  },
  {
    id: 'draw-starter-50',
    title: 'Starter Pack',
    subtitle: 'Perfect first open • Instant win',
    prizeAmount: '$50 CASH',
    category: 'cash',
    image: '/assets/cutouts/starter-50.png',
    accentGradient: 'from-lime-400 to-emerald-500',
    isFeatured: false,
    isLive: true,
    endsAt: flashTarget,
    totalEntrants: 1893,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Today • Live Flash',
    description: 'Entry-level pack for new players. Low competition, fast flash draw every hour. Free to open.',
    seedHash: '0x11aa02bc449102b378daef019247cc99318a09fb211',
    tier: 'Flash',
  },
  {
    id: 'draw-bronze-100',
    title: 'Bronze Pack',
    subtitle: 'Daily bronze drop',
    prizeAmount: '$100 CASH',
    category: 'cash',
    image: '/assets/cutouts/bronze-100.png',
    accentGradient: 'from-amber-500 to-orange-600',
    isFeatured: false,
    isLive: false,
    endsAt: dailyTarget,
    totalEntrants: 3245,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Tomorrow • 12:00 PM EST',
    description: 'Bronze tier daily pack. Guaranteed cash winner every day, free entry with Telegram verification.',
    seedHash: '0x22bb03cd559213c489ebf120358dd00429b10fc322',
    tier: 'Daily',
  },
  {
    id: 'draw-silver-250',
    title: 'Silver Pack',
    subtitle: 'Most opened • High odds',
    prizeAmount: '$250 CASH',
    category: 'cash',
    image: '/assets/cutouts/render-hero-sphere.png',
    accentGradient: 'from-slate-400 to-slate-600',
    isFeatured: true,
    isLive: false,
    endsAt: dailyTarget,
    totalEntrants: 5920,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 26 • 9:00 PM EST',
    description: 'Our most popular silver pack. Balanced odds, daily winners, instant Telegram payout.',
    seedHash: '0x33cc04de66a324d59afc231469ee11530c21gd433',
    tier: 'Daily',
  },
  {
    id: 'draw-diamond-2500',
    title: 'Diamond Pack',
    subtitle: 'High roller • $2,500 pool',
    prizeAmount: '$2,500 CASH',
    category: 'cash',
    image: '/assets/cutouts/render-pastel-lottery.png',
    accentGradient: 'from-cyan-400 to-blue-600',
    isFeatured: true,
    isLive: false,
    endsAt: diamondTarget,
    totalEntrants: 11230,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 28 • 8:00 PM EST',
    description: 'Premium diamond tier pack. Massive $2,500 pool with provably fair on-chain draw.',
    seedHash: '0x44dd05ef77b435e60b0d342570ff22641d32he544',
    tier: 'Grand',
  },
  {
    id: 'draw-crypto-750',
    title: 'Crypto Pack',
    subtitle: 'BTC / USDT instant payout',
    prizeAmount: '$750 Crypto',
    category: 'giftcard',
    image: '/assets/cutouts/crypto-750.png',
    accentGradient: 'from-orange-400 to-yellow-500',
    isFeatured: false,
    isLive: true,
    endsAt: liveDrawTarget,
    totalEntrants: 4475,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 25 • Live Draw',
    description: 'Crypto lovers pack. Winner Choice of BTC, ETH or USDT sent instantly to wallet.',
    seedHash: '0x55ee06f088c546f71c1e45368100227452e43if655',
    tier: 'Daily',
  },
  {
    id: 'draw-macbook-air',
    title: 'MacBook Air M3',
    subtitle: '13-inch • 8GB • 256GB',
    prizeAmount: '$1,099 Value',
    category: 'tech',
    image: '/assets/cutouts/macbook-dark.png',
    accentGradient: 'from-zinc-500 to-slate-700',
    isFeatured: false,
    isLive: false,
    endsAt: diamondTarget,
    totalEntrants: 7830,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 28 • 6:00 PM EST',
    description: 'Brand new MacBook Air M3 sealed in box. Free express shipping worldwide.',
    seedHash: '0x66ff07g199d657g82d2f56479211338563f54jg766',
    tier: 'Weekly',
  },
  {
    id: 'draw-airpods-max',
    title: 'AirPods Pro 2 Pack',
    subtitle: 'USB-C • Noise cancelling',
    prizeAmount: '$249 Value',
    category: 'tech',
    image: '/assets/cutouts/airpods-pro.png',
    accentGradient: 'from-sky-400 to-indigo-500',
    isFeatured: false,
    isLive: false,
    endsAt: giftDrawTarget,
    totalEntrants: 2980,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Sep 26 • 4:00 PM EST',
    description: 'AirPods Pro 2 with MagSafe case. Quick daily tech drop, free entry.',
    seedHash: '0x770008h200e768h93e3g67580322449674g65kh877',
    tier: 'Daily',
  },
  {
    id: 'draw-steam-100',
    title: 'Gamer Pack',
    subtitle: '$100 Steam + PSN code',
    prizeAmount: '$100 Gaming',
    category: 'lifestyle',
    image: '/assets/cutouts/gamer-100.png',
    accentGradient: 'from-violet-500 to-purple-700',
    isFeatured: false,
    isLive: true,
    endsAt: flashTarget,
    totalEntrants: 2150,
    maxEntriesPerUser: 1,
    drawDateFormatted: 'Today • Flash Drop',
    description: 'Instant digital gamer pack. $100 Steam wallet or PSN voucher delivered via Telegram.',
    seedHash: '0x881119i311f879i04f4h78691433550785h76li988',
    tier: 'Flash',
  },
];

export const MOCK_WINNERS: Winner[] = [
  {
    id: 'win-1',
    username: '@alex92',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    prizeAmount: '$500 CASH',
    prizeTitle: '$500 Cash Free Giveaway',
    ticketId: '#A82K91',
    drawDateFormatted: 'Sep 18, 2026',
    telegramVerified: true,
    seedHash: '0x7c94b2...82fa',
  },
  {
    id: 'win-2',
    username: '@sophia_m',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    prizeAmount: 'iPhone 15 Pro',
    prizeTitle: 'Apple Tech Spotlight',
    ticketId: '#B19X42',
    drawDateFormatted: 'Sep 11, 2026',
    telegramVerified: true,
    seedHash: '0x33e081...49cd',
  },
  {
    id: 'win-3',
    username: '@david_k',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    prizeAmount: '$1,000 CASH',
    prizeTitle: 'Weekly Gold Pool',
    ticketId: '#C77F90',
    drawDateFormatted: 'Sep 04, 2026',
    telegramVerified: true,
    seedHash: '0x8892fa...11bc',
  },
  {
    id: 'win-4',
    username: '@elena_r',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    prizeAmount: '$250 Gift Card',
    prizeTitle: 'Amazon Digital Voucher',
    ticketId: '#D42L18',
    drawDateFormatted: 'Aug 28, 2026',
    telegramVerified: true,
    seedHash: '0x9923bb...04fa',
  },
  {
    id: 'win-5',
    username: '@marcus_t',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    prizeAmount: 'PlayStation 5',
    prizeTitle: 'Gaming Drop Special',
    ticketId: '#E90A33',
    drawDateFormatted: 'Aug 21, 2026',
    telegramVerified: true,
    seedHash: '0x55018e...291a',
  },
];

export const INITIAL_ENTRIES: Entry[] = [
  {
    id: 'entry-1',
    ticketId: '#A82K91',
    giveawayId: 'draw-live-500',
    giveawayTitle: '$500 CASH Free Giveaway',
    prizeAmount: '$500 CASH',
    drawDateFormatted: 'Sep 25, 2026 • 9:00 PM EST',
    enteredAt: 'Sep 24, 2026',
    status: 'active',
    telegramSynced: true,
    telegramUsername: '@alex92',
  },
  {
    id: 'entry-2',
    ticketId: '#B44J19',
    giveawayId: 'draw-hero-5000',
    giveawayTitle: 'Weekly Grand Pool',
    prizeAmount: '$5,000',
    drawDateFormatted: 'Sep 27, 2026 • 9:00 PM EST',
    enteredAt: 'Sep 23, 2026',
    status: 'active',
    telegramSynced: true,
    telegramUsername: '@alex92',
  },
  {
    id: 'entry-3',
    ticketId: '#C92Q08',
    giveawayId: 'draw-iphone-16',
    giveawayTitle: 'iPhone 16 Pro Max 256GB',
    prizeAmount: '$1,199 Value',
    drawDateFormatted: 'Tomorrow • 8:00 PM EST',
    enteredAt: 'Sep 22, 2026',
    status: 'active',
    telegramSynced: true,
    telegramUsername: '@alex92',
  },
  {
    id: 'entry-4',
    ticketId: '#D11R75',
    giveawayId: 'draw-amazon-250',
    giveawayTitle: '$250 Amazon Gift Card',
    prizeAmount: '$250 Gift Card',
    drawDateFormatted: 'Sep 18, 2026 • 6:00 PM EST',
    enteredAt: 'Sep 16, 2026',
    status: 'completed',
    telegramSynced: true,
    telegramUsername: '@alex92',
  },
];
